# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  solutionDir: azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'what directory are we in now?'

- script: ls -la
  displayName: 'what directories and files in this current Directory?'
  workingDirectory: $(solutionDir)