# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  solutionDir: resources

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'what directory are we in now?'

- script: ls -la
  displayName: 'what directories and files in this current Directory?'

- script: cat index.html
  displayName: 'print out the index file contents'  

- script: cat script.js
  displayName: 'print out the javascript content'
  workingDirectory: $(solutionDir)

- script: cat script.js
  displayName: 'print out the javascript content'
  workingDirectory: $(solutionDir)
- task: AzureStaticWebApp@0
  inputs:
  app_location: '.'
  api_location: 'api'
  azure_static_web_apps_api_token: $(API-TOKEN)